{
 "title": "Cloudflare Network Analytics",
 "time": { "from": "now-4h", "to": "now-2m" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "fifemon-graphql-datasource" },
   { "name": "accountTag", "query": "put-your-account-tag-here" },
   {
    "name": "timeBucket",
    "label": "Time Bucket",
    "query": "1s :  Second,10s : TenSeconds, 1m : Minute,5m : FiveMinutes,15m : FifteenMinutes,1h : Hour"
   },
   { "name": "topN", "label": "Top N", "query": "5,10,20,50" },
   {
    "name": "topSourceAsns",
    "query": {}
   },
   {
    "name": "topColoCodes",
    "query": {}
   },
   {
    "name": "topSourceCountries",
    "query": {}
   },
   {
    "name": "topAttackIDs",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic by Destination Subnet (Packets)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "aliasBy": "$field_dimensions.ipDestinationSubnet",
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.magicTransitNetworkAnalyticsAdaptiveGroups",
     "endTimePath": "endTime",
     "groupBy": "dimensions.ipDestinationSubnet",
     "queryText": "query {\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      magicTransitNetworkAnalyticsAdaptiveGroups(\n        limit: 10000\n        filter: {\n          datetime_geq: \"${__from:date:iso}\"\n          datetime_lt: \"${__to:date:iso}\"\n          outcome: \"pass\"\n        }\n        orderBy: [datetime${timeBucket}_ASC, avg_bitRate${timeBucket}_DESC]\n      ) {\n        dimensions {\n          datetime${timeBucket}\n          ipDestinationSubnet\n        }\n        avg {\n          packetRate${timeBucket}\n        }\n      }\n    }\n  }\n}",
     "timePath": "dimensions.datetime$field_timeBucket"
    }
   ]
  },
  {
   "title": "Traffic by Destination Subnet (Bits)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "aliasBy": "$field_dimensions.ipDestinationSubnet",
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.magicTransitNetworkAnalyticsAdaptiveGroups",
     "endTimePath": "endTime",
     "groupBy": "dimensions.ipDestinationSubnet",
     "queryText": "query {\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      magicTransitNetworkAnalyticsAdaptiveGroups(\n        limit: 10000\n        filter: {\n          datetime_geq: \"${__from:date:iso}\"\n          datetime_lt: \"${__to:date:iso}\"\n          outcome: \"pass\"\n        }\n        orderBy: [datetime${timeBucket}_ASC, avg_bitRate${timeBucket}_DESC]\n      ) {\n        dimensions {\n          datetime${timeBucket}\n          ipDestinationSubnet\n        }\n        avg {\n          bitRate${timeBucket}\n        }\n      }\n    }\n  }\n}",
     "timePath": "dimensions.datetime$field_timeBucket"
    }
   ]
  },
  {
   "title": "Top Source ASNs",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.magicTransitNetworkAnalyticsAdaptiveGroups",
     "endTimePath": "endTime",
     "groupBy": "dimensions.sourceAsn",
     "queryText": "query {\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      magicTransitNetworkAnalyticsAdaptiveGroups(\n        limit: 10000\n        filter: {\n          datetime_geq: \"${__from:date:iso}\"\n          datetime_lt: \"${__to:date:iso}\"\n          sourceAsn_in: [${topSourceAsns:raw}]\n        }\n        orderBy: [datetime${timeBucket}_ASC, avg_packetRate${timeBucket}_DESC]\n      ) {\n        dimensions {\n          datetime${timeBucket}\n          sourceAsn\n        }\n        avg {\n          packetRate${timeBucket}\n        }\n      }\n    }\n  }\n}",
     "timePath": "dimensions.$field_timeBucket"
    }
   ]
  },
  {
   "title": "Top Source Countries",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.magicTransitNetworkAnalyticsAdaptiveGroups",
     "endTimePath": "endTime",
     "groupBy": "dimensions.sourceCountry",
     "queryText": "query {\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      magicTransitNetworkAnalyticsAdaptiveGroups(\n        limit: 10000\n        filter: {\n          datetime_geq: \"${__from:date:iso}\"\n          datetime_lt: \"${__to:date:iso}\"\n          sourceCountry_in: [${topSourceCountries:doublequote}]\n        }\n        orderBy: [datetime${timeBucket}_ASC, avg_packetRate${timeBucket}_DESC]\n      ) {\n        dimensions {\n          datetime${timeBucket}\n          sourceCountry\n        }\n        avg {\n          packetRate${timeBucket}\n        }\n      }\n    }\n  }\n}",
     "timePath": "dimensions.$field_timeBucket"
    }
   ]
  },
  {
   "title": "Colo Heatmap",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.magicTransitNetworkAnalyticsAdaptiveGroups",
     "endTimePath": "endTime",
     "queryText": "query {\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      magicTransitNetworkAnalyticsAdaptiveGroups(\n        limit: 10000\n        filter: {\n          datetime_geq: \"${__from:date:iso}\"\n          datetime_lt: \"${__to:date:iso}\"\n          outcome: \"pass\"\n        }\n      ) {\n        dimensions {\n          coloGeohash\n          coloCode\n        }\n        avg {\n          bitRate: bitRate${timeBucket}\n        }\n      }\n    }\n  }\n}"
    }
   ]
  },
  { "title": "dosd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Top Attacks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "aliasBy": "$field_dimensions.attackId",
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.dosdNetworkAnalyticsAdaptiveGroups",
     "endTimePath": "endTime",
     "groupBy": "dimensions.attackId",
     "queryText": "query {\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      dosdNetworkAnalyticsAdaptiveGroups(\n        limit: 10000\n        filter: {\n          datetime_geq: \"${__from:date:iso}\"\n          datetime_lt: \"${__to:date:iso}\"\n          attackId_in: [${topAttackIDs:doublequote}]\n          outcome: \"drop\"\n        }\n        orderBy: [datetime${timeBucket}_ASC, avg_packetRate${timeBucket}_DESC]\n      ) {\n        dimensions {\n          datetime${timeBucket}\n          attackId\n        }\n        avg {\n          packetRate${timeBucket}\n        }\n      }\n    }\n  }\n}",
     "timePath": "dimensions.datetime$field_timeBucket"
    }
   ]
  },
  {
   "title": "Drops by Reason",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "aliasBy": "$field_dimensions.mitigationReason $field_dimensions.protocolState",
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.dosdNetworkAnalyticsAdaptiveGroups",
     "endTimePath": "endTime",
     "groupBy": "dimensions.mitigationReason,dimensions.protocolState",
     "queryText": "query {\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      dosdNetworkAnalyticsAdaptiveGroups(\n        limit: 10000\n        filter: {\n          datetime_geq: \"${__from:date:iso}\"\n          datetime_lt: \"${__to:date:iso}\"\n          outcome: \"drop\"\n        }\n        orderBy: [datetime${timeBucket}_ASC, avg_packetRate${timeBucket}_DESC]\n      ) {\n        dimensions {\n          datetime${timeBucket}\n          mitigationReason\n          protocolState\n        }\n        avg {\n          packetRate${timeBucket}\n        }\n      }\n    }\n  }\n}",
     "timePath": "dimensions.datetime$field_timeBucket"
    }
   ]
  },
  { "title": "flowtrackd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "New TCP Connections by Destination Subnet",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "aliasBy": "$field_dimensions.ipDestinationSubnet",
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.flowtrackdNetworkAnalyticsAdaptiveGroups",
     "endTimePath": "endTime",
     "groupBy": "dimensions.ipDestinationSubnet",
     "queryText": "query {\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      flowtrackdNetworkAnalyticsAdaptiveGroups(\n        limit: 10000\n        filter: {\n          datetime_geq: \"${__from:date:iso}\"\n          datetime_lt: \"${__to:date:iso}\"\n          outcome: \"pass\"\n          protocolState: \"NEW\"\n        }\n        orderBy: [datetime${timeBucket}_ASC, avg_bitRate${timeBucket}_DESC]\n      ) {\n        dimensions {\n          datetime${timeBucket}\n          ipDestinationSubnet\n        }\n        avg {\n          packetRate${timeBucket}\n        }\n      }\n    }\n  }\n}",
     "timePath": "dimensions.datetime$field_timeBucket"
    }
   ]
  },
  {
   "title": "Drops by Destination Subnet",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "aliasBy": "$field_dimensions.ipDestinationSubnet ($field_dimensions.mitigationReason)",
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.flowtrackdNetworkAnalyticsAdaptiveGroups",
     "endTimePath": "endTime",
     "groupBy": "dimensions.ipDestinationSubnet,dimensions.mitigationReason",
     "queryText": "query {\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      flowtrackdNetworkAnalyticsAdaptiveGroups(\n        limit: 10000\n        filter: {\n          datetime_geq: \"${__from:date:iso}\"\n          datetime_lt: \"${__to:date:iso}\"\n          outcome: \"drop\"\n        }\n        orderBy: [datetime${timeBucket}_ASC, avg_bitRate${timeBucket}_DESC]\n      ) {\n        dimensions {\n          datetime${timeBucket}\n          ipDestinationSubnet\n          mitigationReason\n        }\n        avg {\n          packetRate${timeBucket}\n        }\n      }\n    }\n  }\n}",
     "timePath": "dimensions.datetime$field_timeBucket"
    }
   ]
  },
  { "title": "Magic Firewall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Drops by Rule ID",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "aliasBy": "$field_dimensions.ruleId",
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.magicFirewallNetworkAnalyticsAdaptiveGroups",
     "endTimePath": "endTime",
     "groupBy": "dimensions.ruleId",
     "queryText": "query {\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      magicFirewallNetworkAnalyticsAdaptiveGroups(\n        limit: 10000\n        filter: {\n          datetime_geq: \"${__from:date:iso}\"\n          datetime_lt: \"${__to:date:iso}\"\n          outcome: \"drop\"\n        }\n        orderBy: [datetime${timeBucket}_ASC, avg_bitRate${timeBucket}_DESC]\n      ) {\n        dimensions {\n          datetime${timeBucket}\n          ruleId\n        }\n        avg {\n          packetRate${timeBucket}\n        }\n      }\n    }\n  }\n}",
     "timePath": "dimensions.datetime$field_timeBucket"
    }
   ]
  },
  {
   "title": "Drops by Destination Subnet",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "aliasBy": "$field_dimensions.ipDestinationSubnet",
     "constant": 6.5,
     "dataPath": "viewer.accounts.0.magicFirewallNetworkAnalyticsAdaptiveGroups",
     "endTimePath": "endTime",
     "groupBy": "dimensions.ipDestinationSubnet",
     "queryText": "query {\n  viewer {\n    accounts(filter: {accountTag: \"${accountTag}\"}) {\n      magicFirewallNetworkAnalyticsAdaptiveGroups(\n        limit: 10000\n        filter: {\n          datetime_geq: \"${__from:date:iso}\"\n          datetime_lt: \"${__to:date:iso}\"\n          outcome: \"drop\"\n        }\n        orderBy: [datetime${timeBucket}_ASC, avg_bitRate${timeBucket}_DESC]\n      ) {\n        dimensions {\n          datetime${timeBucket}\n          ipDestinationSubnet\n        }\n        avg {\n          packetRate${timeBucket}\n        }\n      }\n    }\n  }\n}",
     "timePath": "dimensions.datetime$field_timeBucket"
    }
   ]
  }
 ]
}